### PR TITLE
Update attributes.json

### PR DESCRIPTION
**Pull request by ian4uh**
Resolves error when a Glyph is generated with no level selected. temp solution for case No lower case conversion of "None" for Levels in the attributes.json.

### CODE REVIEW

**Comment by Ludicro** [comment]
I reviewed this and could not replicate the issue with the current file so I don't see the functionality of this commit
Screenshot 2024-12-13 172728

**Comment by ian4uh** [comment]
Here's the error that i was getting in my console. Might be my Venv(?) gonna try to troubleshoot that now.

As soon as I changed the level: "None" to lower case it was fine/working

```
PS %UserProfile%\Documents\GitHub\GlyphForge> & %UserProfile%/Documents/GitHub/GlyphForge/venv/Scripts/python.exe %UserProfile%/Documents/GitHub/GlyphForge/app.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "%UserProfile%\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "%UserProfile%\Documents\GitHub\GlyphForge\app.py", line 231, in generate_spell
    image = self.create_spell_image(level, rang, area, dtype, school, duration,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "%UserProfile%\Documents\GitHub\GlyphForge\app.py", line 327, in create_spell_image
    writer.draw_spell(level, rang, area, dtype, school, duration, condition, concentration, ritual, shape, lineType, include_conditions=include_conditions, savename=buf)
  File "%UserProfile%\Documents\GitHub\GlyphForge\GlyphEngine\writer.py", line 164, in draw_spell
    i_levels = levels.index(str(level))
               ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'none' is not in list
```

**Comment by ian4uh** [comment]
Nope Reloaded everything, as soon as I put in that "None" back into the JSON, it fails for me. with the above error in console. Double check your dropdown to see if your attributes have a capitol listed from the JSON vs the initial load of the dropdown menu from TKinter:
image

**Comment by Ludicro** [comment]
I have fixed this issue. The issue was a line I left in from when it was in separate text files converting the values to lowercase. I removed those lines and the issue has been resolved in my testing. Update your copy and let me know if you're still getting it.

**Pull request closed without merging**
